### PR TITLE
calculate climatologies and residuals

### LINKED ISSUE #2: calculation of climatologies
responsible: @mdaber, @konradmayer, @tjurlina

### LINKED ISSUE #3: calculation of standardized anomalies
responsible: @mdaber, @konradmayer, @tjurlina

### PR DESCRIPTION
**Pull request by konradmayer**
This fits pixelwise models representing climatologies with a seasonality and trend component (on, per hour partitioned data) and calculates anomalies (residuals).

**TODOS**:
- [x] code review
- [x] parametrize over data source (to apply to cerra as well)

The modelling seems to work, here example images 

of the predictions (red) above the timeseries (black) of a single pixel (idx 20, 20):
image

as well in space of a single timestep (idx 1000)

for mu

image

and sd

image

### CODE REVIEW

**Comment by konradmayer** [comment]
models are currently saved as rds, writing this file is slow and demands a lot of space (5.8 GB for the small subset as proposed by the spanish team). @mdaber, do you think its a good idea to save only the coefficients instead?

**Comment by konradmayer** [comment]
I fear that this doesn't scale very well. RAM demands are below 10GB currently with the small domain for ERA5.
To calculate this on the whole CERRA domain, this either needs to be run on a very potent machine or data separated into "tiles" beforehand - e.g. using [`cdo distgrid`](https://code.mpimet.mpg.de/projects/cdo/embedded/index.html#x1-1550002.2.13) (and recombined afterwards again with `collgrid`)

**Comment by r3xth0r** [comment]
> models are currently saved as rds, writing this file is slow and demands a lot of space (5.8 GB for the small subset as proposed by the spanish team). @mdaber, do you think its a good idea to save only the coefficients instead?

Using `qs::qsave()` ([CRAN](https://cran.r-project.org/web/packages/qs/index.html)) would definitely speed up the process of saving / reading files substantially. However, this would consume even more disk space...

**Comment by konradmayer** [comment]
> > models are currently saved as rds, writing this file is slow and demands a lot of space (5.8 GB for the small subset as proposed by the spanish team). @mdaber, do you think its a good idea to save only the coefficients instead?
> 
> Using `qs::qsave()` ([CRAN](https://cran.r-project.org/web/packages/qs/index.html)) would definitely speed up the process of saving / reading files substantially. However, this would consume even more disk space...

I doubt that we really need the full models, and the coefficients could be saved as netcdf for consistency (+language agnostic). However, this must be decided by @mdaber, as he beter knows what he needs after the SAMOS model.
For the exercise on the small subset domain the time and size of these files don't really matter, so i would go for the most convenient rather than the most efficient option.

**Comment by mdaber** [comment]
> models are currently saved as rds, writing this file is slow and demands a lot of space (5.8 GB for the small subset as proposed by the spanish team). @mdaber, do you think its a good idea to save only the coefficients instead?

Sorry I forgot to mention, but I usually delete a lot of thinks to make it smaller while saving, such as 
 attr(fit2$terms$location, '.Environment') <- attr(fit2$terms$scale, '.Environment') <- attr(fit2$terms$full, '.Environment') <- NULL
 fit2$residuals <- fit2$fit2ted.values <- fit2$model <- fit2$link$scale$dmu.deta <- fit2$control$start <- fit2$formula <- NULL
You probably have a nicer way to do it but that makes the objects way smaller

**Comment by konradmayer** [comment]
For completeness, here a plot of a single pixel (10, 10)  of the residuals (standardized anomalies) for the 15 lead time output:

image

**Comment by mdaber** [comment]
> For completeness, here a plot of a single pixel (10, 10) of the residuals (anomalies) for the 15 lead time output:
> 
> image

Is it anomalies or standardized anomalies?

**Comment by konradmayer** [comment]
These are standardized anomalies, of course the output of the [code you find within this PR](https://github.com/ECMWFCode4Earth/tesserugged/blob/climatology/dev/preprocessing/climatology_residuals.R#L87)

**Comment by konradmayer** [comment]
> attr(fit2$terms$location, '.Environment') <- attr(fit2$terms$scale, '.Environment') <- attr(fit2$terms$full, '.Environment') <- NULL
> fit2$residuals <- fit2$fit2ted.values <- fit2$model <- fit2$link$scale$dmu.deta <- fit2$control$start <- fit2$formula <- NULL

The [`butcher`](https://butcher.tidymodels.org/) might be useful here

**Comment by konradmayer** [comment]
> > models are currently saved as rds, writing this file is slow and demands a lot of space (5.8 GB for the small subset as proposed by the spanish team). @mdaber, do you think its a good idea to save only the coefficients instead?
> 
> Sorry I forgot to mention, but I usually delete a lot of thinks to make it smaller while saving, such as attr(fit2$terms$location, '.Environment') <- attr(fit2$terms$scale, '.Environment') <- attr(fit2$terms$full, '.Environment') <- NULL fit2$residuals <- fit2$fit2ted.values <- fit2$model <- fit2$link$scale$dmu.deta <- fit2$control$start <- fit2$formula <- NULL You probably have a nicer way to do it but that makes the objects way smaller

This reduces the object size of each model object from 41.11 MB to 29.94 kB

**Comment by konradmayer** [comment]
> > attr(fit2$terms$location, '.Environment') <- attr(fit2$terms$scale, '.Environment') <- attr(fit2$terms$full, '.Environment') <- NULL
> > fit2$residuals <- fit2$fit2ted.values <- fit2$model <- fit2$link$scale$dmu.deta <- fit2$control$start <- fit2$formula <- NULL
> 
> The [`butcher`](https://butcher.tidymodels.org/) might be useful here

looks like `crch` is not included, but if we are motivated we could [add them to butcher](https://butcher.tidymodels.org/articles/adding-models-to-butcher.html)

**Comment by mdaber** [comment]
I am not a 100% with tydiverse but i looks to be right

**Pull request merged**
